name: CI

on:  
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  workflow_dispatch:

permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to merge branches
    contents: write

jobs:
  buildplusTest:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:  
        python-version: [3.9.21, 3.10.16, 3.11.11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up 
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
          cache: 'pip'
      - name: Install Dependencies
        run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt 
         pip install tox
         pip install ruff
         pip install pytest pytest-cov
      - name: Lint code with Ruff
        run: ruff check --output-format=github --target-version=py39
      - name: Check code formatting with Ruff
        run: ruff format --diff --target-version=py39
        continue-on-error: true
      - name: Run Test
        run : |
          ls -la
          pytest OperationsTest.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
  merge:
    runs-on: ubuntu-latest
    needs:  buildplusTest
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Git
        run: |
          git config --global user.email "mergeBot@github.com"
          git config --global user.name "MergeBot"
      - name: Create temporary branch and push it
        run: |
          TEMP_BRANCH="merge-dev-into-main-$(date +%s)"
          git fetch origin
          git checkout -b $TEMP_BRANCH origin/dev
          git push origin $TEMP_BRANCH
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: ${{ steps.create_branch.outputs.branch }}
          title: "Merge dev into main"
          body: "Automated PR to merge changes from dev into main after successful CI"
          draft: false

      